name: Integrity check

on:
  push:
    branches:
      - master
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
  schedule:
    - cron: '1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 8.1

    - name: Install composer deps
      run: |
        composer create-project nette/code-checker temp/code-checker ^3 --no-progress
        composer create-project nette/coding-standard temp/coding-standard ^3 --no-progress

        # Install app deps
        composer install --no-interaction --prefer-dist

    - name: The PHP Security Checker
      uses: symfonycorp/security-checker-action@v2

    - name: Check PHPStan rules
      run: composer phpstan
